[package]
name = "autoswe"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
reqwest = { version = "0.11", features = ["json"] }
tokio = { version = "1", features = ["full"] }
futures = "0.3"
async-trait = "0.1"
base64 = "0.21"
dotenvy = "0.15"
crossterm = "0.27"
ratatui = "0.26.1"
atty = "0.2"
url = "2.5"
html2md = "0.2"
chrono = "0.4"
dirs = "5.0"
thiserror = "1.0"
clipboard = "0.5"
regex = "1.10.3"
ctrlc = "3.4.1"