[package]
name = "autoswe"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
ureq = { version = "2.9", features = ["json"] }
base64 = "0.21"
dotenvy = "0.15"
crossterm = "0.27"
url = "2.5"
html2md = "0.2"
chrono = "0.4"
dirs = "5.0"