[workspace]
members = [".", "server"]

[package]
name = "termineer"
version = "0.1.17"
edition = "2021"
license = "MIT"

[dependencies]
anyhow = "1.0"  # Error handling
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
reqwest = { version = "0.11", features = ["json"] }
tokio = { version = "1", features = ["full"] }
futures = "0.3"
async-trait = "0.1"
dotenvy = "0.15"
crossterm = "0.27"
ratatui = "0.26.1"
atty = "0.2"
chrono = "0.4"
thiserror = "1.0"
ctrlc = "3.4.1"
lazy_static = "1.4.0"  # For static initialization
handlebars = "6.3.1"  # Handlebars templating
urlencoding = "2.1.3"  # URL encoding for API requests
aes-gcm = "0.10.3"     # AES-GCM encryption
obfstr = "0.4.3"       # String obfuscation for sensitive constants
rand = "0.8.5"         # For random number generation
dirs = "5.0.1"         # For getting user directories
webbrowser = "0.8.11"  # For opening browser in OAuth flow
axum = "0.7.4"         # For creating local OAuth callback server
base64 = "0.13.0"      # For encoding/decoding base64 in OAuth flow
glob = "0.3.1"         # For glob pattern matching in autoinclude feature
scraper = "0.23.1"

[build-dependencies]
aes-gcm = "0.10.3"     # AES-GCM encryption
walkdir = "2.4.0"      # For walking directories in build script
quote = "1.0.33"       # For code generation
proc-macro2 = "1.0.78" # Required by quote
