[package]
name = "autoswe"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"  # Error handling
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
reqwest = { version = "0.11", features = ["json"] }
tokio = { version = "1", features = ["full"] }
tokio-tungstenite = "0.19"  # WebSocket support for MCP
futures = "0.3"
async-trait = "0.1"
base64 = "0.21"
dotenvy = "0.15"
crossterm = "0.27"
ratatui = "0.26.1"
atty = "0.2"
url = "2.5"
chrono = "0.4"
thiserror = "1.0"
ctrlc = "3.4.1"
arboard = "3.2.1"  # Clipboard support
lazy_static = "1.4.0"  # For static initialization
handlebars = "6.3.1"  # Handlebars templating
urlencoding = "2.1.3"  # URL encoding for API requests