version: '3'

services:
  # Database service
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: termineer
      POSTGRES_PASSWORD: development
      POSTGRES_DB: termineer
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U termineer"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Server service
  server:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgres://termineer:development@db:5432/termineer
      - JWT_SECRET=developmentSecret123
      - GOOGLE_CLIENT_ID=mock_client_id_for_testing
      - GOOGLE_CLIENT_SECRET=mock_client_secret_for_testing
      - REDIRECT_URL=http://localhost:3000/auth/google/callback
      - FRONTEND_URL=http://localhost:8732
      - PORT=3000
      - ENVIRONMENT=development
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data: