# Test deployment of Termineer server

app = "autoswe-server-test"
primary_region = "sjc"

[build]
dockerfile = "Dockerfile.workspace"

[http_service]
  internal_port = 8080
  force_https = true
  auto_start_machines = true
  auto_stop_machines = true
  min_machines_running = 0
  processes = ["app"]

[env]
  PORT = "8080"
  ENVIRONMENT = "test"
  HOST = "autoswe-server-test.fly.dev"
  RUST_LOG = "debug,sqlx=info"
  # We're using a dummy DATABASE_URL in our app now, but it's good to set this to something valid
  # Fly will automatically set DATABASE_URL if we attach a database

[checks]
  [checks.health]
    port = 8080
    type = "http"
    interval = "10s"
    timeout = "2s"
    grace_period = "5s"
    method = "get"
    path = "/health"
    protocol = "http"

[[mounts]]
  source = "autoswe_test_data"
  destination = "/data"