# fly.toml file generated for autoswe-server

app = "autoswe-server"
primary_region = "iad"
kill_signal = "SIGINT"
kill_timeout = 5

[env]
  PORT = "3000"
  ENVIRONMENT = "production"
  REDIRECT_URL = "https://autoswe-server.fly.dev/auth/google/callback"
  FRONTEND_URL = "http://localhost:8732"
  RUST_LOG = "info,sqlx=warn"
  DATABASE_URL = "sqlite:data/autoswe.db"

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[build]
  dockerfile = "Dockerfile.prod"

[mounts]
  source = "autoswe_data"
  destination = "/home/appuser/data"

[[services]]
  internal_port = 3000
  protocol = "tcp"
  auto_start_machines = true
  auto_stop_machines = true
  min_machines_running = 1
  max_machines_running = 3

  [services.concurrency]
    hard_limit = 500
    soft_limit = 250

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

  [services.http_checks]
    interval = "10s"
    timeout = "2s"
    grace_period = "5s"
    method = "get"
    path = "/health"
    protocol = "http"
    restart_limit = 0