name: Continuous Integration

# This workflow runs tests for every push and pull request to ensure code quality

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Cache Rust dependencies
        uses: swatinem/rust-cache@v2
      
      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install Linux dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libdbus-1-dev pkg-config
      
      - name: Run tests
        run: cargo test --all
        
      - name: Run linting checks
        run: cargo clippy -- -D warnings